### ISSUE TITLE
Connection Bug

### ISSUE THREAD

**Issue by Swang007** [LiveFlightApp/Connect-OSX#1]
Everything is setup as it should be, but Infinite Flight simply won't connect to LFC. LFC just sits there with the scrolling wheel and never connects. I'd send a log but it doesn't save a log to my desktop either. I think logs only start once you actually send input to it, which you can only do with a connection to IF.

**Comment by yuvalk1** [comment]
LFC does connect to Infinite Flight. I have the same problem as you, but after I start flying and press "g'' on my mac's keyboard it toggles landing gears. i suppose the loading problem is because it doesn't have a trigger that tells it when to stop searching.

**Comment by carmichaelalonso** [comment]
@yuvalk1 it stops searching (closes the UDP connection) when it receives a packet from Infinite Flight Connect.

**Comment by yuvalk1** [comment]
@carmichaelalonso I got an error in UDPReciever.m "Method definition for 'didReceiveData:fromAddress:withFilterContext:' not found" maybe that's the reason for the problem?

**Comment by carmichaelalonso** [comment]
@yuvalk1 that could be it yes. Do you have the console output from Xcode you can paste into a new issue?

**Comment by carmichaelalonso** [comment]
Fixed in aa4dfb592c8dd88b5538a300f1b6f92bf513d883.
