### ISSUE TITLE
Logitech WingMan Attack 2 joystick isn't recognised

### ISSUE THREAD

**Issue by yuvalk1** [LiveFlightApp/Connect-OSX#3]
I know it says that not all joysticks are supported, but since that one is a simple Plug & Play one i don't see no reason that it won't recognise it. Is this a problem with this joystick or a bug?

note: i got some code errors in the joystick code which i fixed but it didn't seem to have any effect. also the consoles says nothing about a connection of a device.

**Comment by carmichaelalonso** [comment]
The log should say something like "joystick connected" - check to see in System Report (via OS X about) to see if it detects the joystick plugged in. If so, maybe try it with something like X-Plane. That style of joystick should work out of the box...

**Comment by yuvalk1** [comment]
The joystick works perfectly, i'm using it all the time on FSX, and it worked on X-Plane on my mac the last time i tried. Same goes for a steering wheel. it just doesn't work on LiveFlight.

**Comment by carmichaelalonso** [comment]
Hmm ok... This is hard to repro since I don't have the hardware...

**Comment by yuvalk1** [comment]
You can tell me how it recognise the joystick and I'll try to find the problem.

**Comment by yuvalk1** [comment]
i've just updated OSX and it seems to be working now. Betas keep ruining stuff ;)

**Comment by carmichaelalonso** [comment]
Ah, excellent! Strange issue, was going to try and find a joystick test tool for you... :)
